trigger:
  batch: true
  branches:
    include:
      - main
      - release/*

resources:
  repositories:
    - repository: niveristand-custom-device-build-tools
      type:       github
      ref:        main
      endpoint:   ni (2)
      name:       ni/niveristand-custom-device-build-tools
# Pipeline Completion Triggers:
  pipelines:
    - pipeline: VeristandMessageLibrary
      source:   ni.niveristand-custom-device-message-library
      trigger:  true

stages:
  - template: azure-templates/stages.yml
    parameters:
      lvVersionsToBuild: 
        - version: '2020'
          bitness: '32-bit'
        - version: '2021'
          bitness: '64bit'
        - version: '2023'
          bitness: '64bit'

      dependencies:
        - source: '\\nirvana\Measurements\VeriStandAddons\messaging_library'
          file: 'CDMessaging.lvlibp'
          destination: 'Includes'

      buildSteps:
        - projectLocation: 'Source\TestProject.lvproj'
          buildOperation: 'ExecuteBuildSpec'
          target: 'My Computer'
          buildSpec: 'BuildSpec'

        - projectLocation: 'Source\TestProject.lvproj'
          buildOperation: 'ExecuteBuildSpec'
          target: 'Linux x64'
          buildSpec: 'BuildSpec'

        - projectLocation: 'Source\TestProject.lvproj'
          buildOperation: 'ExecuteBuildSpec'
          target: 'Linux x64'
          buildSpec: 'LinuxOnlyBuildSpec'

      releaseVersion: '23.0.0'
      quarterlyReleaseVersion: '2023 Q1'
      buildOutputLocation: 'Built'
      archiveLocation: '\\daqserver\temp\papower\Measurements\VeriStandAddons\imitation-cd'

      pack: true
      packages:
        - controlFileName: 'control'
          payloadMaps:
            - payloadLocation: 'Built'
              installLocation: 'documents\National Instruments\NI VeriStand $(lvVersion)\SLSC Plugins\Modules'
