# File: azure-pipelines.yml

trigger:
  batch: true
  branches:
    include:
      - main
      - release/*

resources:
  repositories:
    - repository: niveristand-custom-device-build-tools
      type: github
      ref: main
      endpoint: ni (2)
      name: ni/niveristand-custom-device-build-tools

pool:
  name: custom-device-temp
  demands:
    - agent.os -equals Windows_NT

# Custom Device-specific Parameters
parameters:
    # Custom Device Name
  - name:    customDevice
    type:    string
    default: imitation-cd
    # LabVIEW Versions to Build
  - name:    lvVersions
    type:    object
    default:
      - '2020'
      - '2021'
      - '2023'
# Build Output Location
  - name:    buildOutputLocation
    type:    string
    default: 'Built'
# Post-build Archive Location
  - name:    archiveLocation
    type:    string
    default: '\\nirvana\temp\papower\Measurements\VeriStandAddons\imitation-cd'
# Custom Device Build Steps (project location, LabVIEW CLI Build operation)
  - name:    buildSteps
    type:    object
    default:
      - [projectLocation: 'Source\TestProject.lvproj', 
         buildOperation: 'ExecuteAllBuildSpecs', 
         target: '', 
         buildSpec: '']

stages:
  - stage: build
    jobs:
      - ${{ each lvVersion in parameters.lvVersions }}:
        - job:
          displayName: Build ${{ parameters.customDevice }} for LabVIEW ${{ lvVersion }}
          steps:
            - template: azure-templates\pre-job-steps.yml # Configure variables, check out repos, Clear cache
              parameters:
                customDevice: ${{ parameters.customDevice }}
                lvVersion:    ${{ lvVersion }}
            - ${{ each buildStep in parameters.buildSteps }}:
              - template: azure-templates\build-op-steps.yml # config file and build specs
                parameters:
                  projectLocation: ${{ buildStep.projectLocation }}
                  buildOperation:  ${{ buildStep.buildOperation }}
                  target:          ${{ buildStep.target }}
                  buildSpec:       ${{ buildStep.buildSpec }}
            - template: azure-templates\post-job-steps.yml # nipkg and archive
              parameters:
                buildOutputLocation: ${{ parameters.buildOutputLocation }}
                archiveLocation:     ${{ parameters.archiveLocation     }}
                pack:                false