# test/POC pipeline for GitHub Veristand Custom Devices migration out of Jenkins

# Triggering: if there is a change to one of the branches below, run the pipeline
trigger:
  batch: true
  branches:
    include:
      - main
      - release/*

# Agent Pool:  choose an agent that meets the following requirements
pool:
  name: Drivers-NIBuildFarm-RFMIBUILD
  demands:
    - agent.os -equals Windows_NT

# Repositories: include build tools (custom device repo included by default)
resources:
  repositories:
    - repository: niveristand-custom-device-build-tools
      type: github
      ref: main
      endpoint: ni (2)
      name: ni/niveristand-custom-device-build-tools

# Currently, no parallelism is needed so far, and no stages are needed so far
jobs:
  - job: build_for_lv2020
    displayName: Build for LabVIEW 2020
    steps:
        # 1: Checkout
      - checkout: self
        displayName: checkout custom device repository
      - checkout: niveristand-custom-device-build-tools
        displayName: checkout build tools repository
        # 2: Interpret TOML (?)
      - script: echo "in the future, do prebuild steps"
        displayName: nothing for now
      - powershell: cd niveristand-custom-device-build-tools\resources; ls
        displayName: build-tools verification
      - powershell: cd imitation-cd; ls
        displayName: cd verification
      - script: copy "imitation-cd\resources\LabVIEW.ini" "C:\Program Files (x86)\National Instruments\LabVIEW 2020\LabVIEW.ini"
        # 3: Build Components
      - script: LabVIEWCLI -PortNumber "3363" -LabVIEWPath "C:\Program Files (x86)\National Instruments\LabVIEW 2020\LabVIEW.exe" -AdditionalOperationDirectory "niveristand-custom-device-build-tools\lv\operations" -OperationName "ExecuteBuildSpec" -ProjectPath "imitation-cd\Source\TestProject.lvproj" -TargetName "My Computer" -BuildSpecName "BuildSpec" -LogFilePath "%cd%\imitation-cd\lvBuildSpec_BuildSpec.log"
        displayName: Build Test Project Windows build specification
      - script: LabVIEWCLI -PortNumber "3363" -LabVIEWPath "C:\Program Files (x86)\National Instruments\LabVIEW 2020\LabVIEW.exe" -OperationName "ExecuteBuildSpec" -ProjectPath "imitation-cd\Source\TestProject.lvproj" -TargetName "Linux x64" -BuildSpecName "BuildSpec"
        displayName: Build Test Project Linux build specification 1
      - script: LabVIEWCLI -PortNumber "3363" -LabVIEWPath "C:\Program Files (x86)\National Instruments\LabVIEW 2020\LabVIEW.exe" -OperationName "ExecuteBuildSpec" -ProjectPath "imitation-cd\Source\TestProject.lvproj" -TargetName "Linux x64" -BuildSpecName "LinuxOnlyBuildSpec"
        displayName: Build Test Project Linux build specification 2
        # 4: Archive
      - script: echo "in the future, do archive steps"
        displayName: nothing for now
      - script: chdir
        displayName: confirm checkouts are still there