trigger:
  batch: true
  branches:
    include:
      - main
      - release/*

resources:
  repositories:
    - repository: niveristand-custom-device-build-tools
      type:       github
      ref:        main
      endpoint:   ni (2)
      name:       ni/niveristand-custom-device-build-tools

  pipelines:
    - pipeline: VeristandMessageLibrary
      source:   ni.niveristand-custom-device-message-library
      trigger:  true

pool:
  name: custom-device-temp # TEMPORARY, eventually use an official build pool of custom device agents
  demands:
    - agent.os -equals Windows_NT

stages:
  - template: azure-templates/stages-template.yml # TEMPORARY, Point to imitation-cd instead of build-tools
    parameters:
      lvVersionsToBuild: 
        - version: '2020'
          bitness: '32bit'
        - version: '2021'
          bitness: '64bit'
        - version: '2023'
          bitness: '64bit'

      releaseInfo:
        - releaseVersion: '23.0.0'
          quarterlyReleaseVersion: '2023 Q1'

      dependencies:
        - source: '\\nirvana\Measurements\VeriStandAddons\messaging_library'
          file: 'CDMessaging.lvlibp'
          destination: 'Includes'

      buildSteps:
        - projectLocation: 'Source\TestProject.lvproj'
          buildOperation: 'ExecuteBuildSpec'
          target: 'My Computer'
          buildSpec: 'BuildSpec'

        - projectLocation: 'Source\TestProject.lvproj'
          buildOperation: 'ExecuteBuildSpec'
          target: 'Linux x64'
          buildSpec: 'BuildSpec'

        - projectLocation: 'Source\TestProject.lvproj'
          buildOperation: 'ExecuteBuildSpec'
          target: 'Linux x64'
          buildSpec: 'LinuxOnlyBuildSpec'

      buildOutputLocation: 'Built'
      archiveLocation: '\\daqserver\temp\papower\Measurements\VeriStandAddons\imitation-cd'

      packages:
        - controlFileName: 'control'
          payloadMaps:
            - payloadLocation: 'Built'
              installLocation: 'documents\National Instruments\NI VeriStand $(lvVersion)\SLSC Plugins\Modules'
