# test/POC pipeline for GitHub Veristand Custom Devices migration out of Jenkins

# Triggering: if there is a change to one of the branches below, run the pipeline
trigger:
  batch: true
  branches:
    include:
      - main
      - release/*

# Repositories: include build tools (custom device repo included by default)
resources:
  repositories:
    - repository: niveristand-custom-device-build-tools
      type: github
      ref: main
      endpoint: ni (2)
      name: ni/niveristand-custom-device-build-tools

# Pipeline-level Parameters
parameters:
  - name: agentPool
    type: string
    default: Drivers-NIBuildFarm-RFMIBUILD
  - name: buildToolsRepo
    type: string
    default: niveristand-custom-device-build-tools

stages:
  - stage: build

  # Agent Pool:  choose an agent that meets the following requirements
    pool:
      name: ${{ parameters.agentPool }}
      demands:
        - agent.os -equals Windows_NT

    # Currently, no parallelism is needed so far, and no stages are needed so far
    jobs:
      - job: build_for_lv2020
        displayName: Build for LabVIEW 2020
        steps:
          - template: templates\build-steps.yaml
            parameters:
              buildToolsRepo: niveristand-custom-device-build-tools
              projectLocation: Source\TestProject.lvproj
              customDevice: imitation-cd
              lvVersion: '2020'
      - job: build_for_lv2021
        displayName: Build for LabVIEW 2021
        steps:
          - template: templates\build-steps.yaml
            parameters:
              buildToolsRepo: niveristand-custom-device-build-tools
              projectLocation: Source\TestProject.lvproj
              customDevice: imitation-cd
              lvVersion: '2021'
      - job: build_for_lv2023
        displayName: Build for LabVIEW 2023
        steps:
          - template: templates\build-steps.yaml
            parameters:
              buildToolsRepo: niveristand-custom-device-build-tools
              projectLocation: Source\TestProject.lvproj
              customDevice: imitation-cd
              lvVersion: '2023'