# File: azure-pipelines.yml

trigger:
  batch: true
  branches:
    include:
      - main
      - release/*

resources:
  repositories:
    - repository: niveristand-custom-device-build-tools
      type: github
      ref: main
      endpoint: ni (2)
      name: ni/niveristand-custom-device-build-tools

pool:
  name: custom-device-temp
  demands:
    - agent.os -equals Windows_NT

# Custom Device-specific Parameters
parameters:
    # Custom Device Name
  - name: customDevice
    type: string
    default: imitation-cd
    # LabVIEW Versions to Build
  - name: lvVersions
    type: object
    default:
      - '2020'
      - '2021'
      - '2023'
    # Custom Device Build Operations
  - name: buildOperations
    type: object
    default:
      - ['Source\TestProject.lvproj', 'ExecuteAllBuildSpecs']

stages:
  - stage: build
    jobs:
      - ${{ each lvVersion in parameters.lvVersions }}:
        - job:
          displayName: Build ${{ parameters.customDevice }} for LabVIEW ${{ lvVersion}}
          steps:
            - template: azure-templates\pre-job-steps.yml # Configure variables, check out repos, Clear cache
              parameters:
                customDevice: ${{ parameters.customDevice }}
                lvVersion: ${{ lvVersion}}
            - ${{ each buildOperation in parameters.buildOperations }}:
              - template: azure-templates\build-op-steps.yml # config file and build specs
                parameters:
                  customDevice: ${{ parameters.customDevice }}
                  lvVersion: ${{ lvVersion }}
                  projectLocations: ${{ buildOperation[0] }}
                  buildOperation: ${{ buildOperation[1] }}
            - template: azure-templates\post-job-steps.yml # nipkg and archive
              parameters:
                customDevice: ${{ parameters.customDevice }}
                lvVersion: ${{ lvVersion}}