trigger:
  batch: true
  branches:
    include:
      - main
      - release/*

resources:
  repositories:
    - repository: niveristand-custom-device-build-tools
      type:       github
      ref:        main
      endpoint:   ni (2)
      name:       ni/niveristand-custom-device-build-tools

pool:
  name: custom-device-temp # TEMPORARY, eventually use an official build pool of custom device agents
  demands:
    - agent.os -equals Windows_NT

# --------- Set Build Parameters ---------
parameters:
    # customDeviceRepoName - Name of the Custom Device Repository on GitHub
  - name:    customDeviceRepoName
    type:    string
    default: imitation-cd

    # lvVersions - each LabVIEW version and bitness combination to build
  - name:    lvVersions
    type:    object
    default:
      - version: '2020'
        bitness: '32-bit'
      - version: '2021'
        bitness: '64-bit'
      # - version: '2023'  TEMPORARY, disable 2023 because it's buggy
      #   bitness: '64-bit'

    # buildSteps - list of each project, buildOperation, target, and buildSpec combination to build 
    # Note: target and buildSpec may be empty for some buildOperations
  - name:    buildSteps
    type:    object
    default:
      - projectLocation: 'Source\TestProject.lvproj'
        buildOperation: 'ExecuteAllBuildSpecs'
        target: ''
        buildSpec: ''

    # buildOutputLocation - location where LV build outputs are stored
  - name:    buildOutputLocation
    type:    string
    default: 'Built'

    # packages - configuration for each nipkg to build
  - name:    packages
    type:    object
    default: 
      - installLocation: 'documents\National Instruments\NI VeriStand $(lvVersion)\SLSC Plugins\Modules'
        controlFileName: 'control'
        payloadLocation: 'Built'

    # archiveLocation - location to store build artifacts for archival
  - name:    archiveLocation
    type:    string
    default: '\\nirvana\temp\papower\Measurements\VeriStandAddons\imitation-cd'

# --------- Call Build Templates ---------
# Note: If custom build steps are needed for a particular custom device, they can be inserted before or after existing templates below
stages:
  - stage: build
    jobs:
      - ${{ each lvVersion in parameters.lvVersions }}:
        - job:
          displayName: Build ${{ parameters.customDeviceRepoName }} for LabVIEW ${{ lvVersion.version }}
          steps:
            - template: azure-templates\pre-job-steps.yml # Configure variables, check out repos, Clear cache
              parameters:
                customDeviceRepoName:  ${{ parameters.customDeviceRepoName }}
                lvVersion:             ${{ lvVersion.version }}
                bitness:               ${{ lvVersion.bitness }} 

            - ${{ each buildStep in parameters.buildSteps }}:
              - template: azure-templates\build-op-steps.yml # config file and build specs
                parameters:
                  projectLocation: ${{ buildStep.projectLocation }}
                  buildOperation:  ${{ buildStep.buildOperation }}
                  target:          ${{ buildStep.target }}
                  buildSpec:       ${{ buildStep.buildSpec }}
                  # dependencies:    ${{ buildStep.dependencies }}


            - template: azure-templates\post-job-steps.yml # nipkg and archive
              parameters:
                packages:            ${{ parameters.packages }}
                buildOutputLocation: ${{ parameters.buildOutputLocation }}
                archiveLocation:     ${{ parameters.archiveLocation }}
                pack:                true