# test/POC pipeline for GitHub Veristand Custom Devices migration out of Jenkins

# Triggering: if there is a change to one of the branches below, run the pipeline
trigger:
  batch: true
  branches:
    include:
      - main
      - release/*

# Repositories: include build tools (custom device repo included by default)
resources:
  repositories:
    - repository: niveristand-custom-device-build-tools
      type: github
      ref: main
      endpoint: ni (2)
      name: ni/niveristand-custom-device-build-tools

# Pipeline-level Variables
variables:
  agentPool: Drivers-NIBuildFarm-RFMIBUILD
  buildToolsRepo: niveristand-custom-device-build-tools
  lvPath: 'TBD'

# Use Stages so that each build runs on a different agent to avoid file conflicts durring parallel builds
stages:
# -----Stage: Build LabVIEW 2020-----
  - stage: build_for_lv2020
    dependsOn: [] # Run in parallel with other stages
    displayName: Build for LabVIEW 2020
    pool:
      name: ${{ variables.agentPool }}
      demands:
        - agent.os -equals Windows_NT
      steps:
        - template: templates\build-steps.yaml
          parameters:
            buildToolsRepo: ${{ variables.buildToolsRepo }}
            projectLocation: Source\TestProject.lvproj
            customDevice: imitation-cd
            lvVersion: '2020'
            bitness: '32'
# -----Stage: Build LabVIEW 2021-----
  - stage: build_for_lv2021
    dependsOn: [] # Run in parallel with other stages
    displayName: Build for LabVIEW 2020
    pool:
      name: ${{ variables.agentPool }}
      demands:
        - agent.os -equals Windows_NT
      steps:
        - template: templates\build-steps.yaml
          parameters:
            buildToolsRepo: ${{ variables.buildToolsRepo }}
            projectLocation: Source\TestProject.lvproj
            customDevice: imitation-cd
            lvVersion: '2021'
            bitness: '64'
# -----Stage: Build LabVIEW 2023-----
  - stage: build_for_lv2023
    dependsOn: [] # Run in parallel with other stages
    displayName: Build for LabVIEW 2020
    pool:
      name: ${{ variables.agentPool }}
      demands:
        - agent.os -equals Windows_NT
      steps:
        - template: templates\build-steps.yaml
          parameters:
            buildToolsRepo: ${{ variables.buildToolsRepo }}
            projectLocation: Source\TestProject.lvproj
            customDevice: imitation-cd
            lvVersion: '2023'
            bitness: '64'