parameters:
  # lvVersionsToBuild: list of {version, bitness}
  - name: lvVersionsToBuild
    type: object

  # buildSteps: list of {projectLocation, buildOperation, target, buildSpec}
  - name: buildSteps
    type: object
  # dependencies (optional): list of {source, file, destination}
  - name: dependencies
    type: object
    default:
      - file: ''
  # packages: list of {controlFileName, payloadMaps: list of {payloadLocation, installLocation} }
  - name: packages
    type: object
  # strings (releaseVersion, quarterlyReleaseVersion, buildOutputLocation, archiveLocation)
  - name: releaseVersion
    type: string
  - name: quarterlyReleaseVersion
    type: string
  - name: buildOutputLocation
    type: string
  - name: archiveLocation
    type: string
  # pack (optional)
  - name: pack
    type: boolean
    default: false

# Note: If custom build steps are needed for a particular custom device, copy this entire template into the azure-pipeline and add steps before/after as needed
stages:
  - stage: build  
    pool:
      name: custom-device-temp # TEMPORARY, eventually use an official build pool of custom device agents
      demands:
        - agent.os -equals Windows_NT
    jobs:
      - ${{ each lvVersionToBuild in parameters.lvVersionsToBuild }}:
        - job: Job${{ lvVersionToBuild.version }}_${{ lvVersionToBuild.bitness }}
          displayName: Build for LabVIEW ${{ lvVersionToBuild.version }}
          steps:
            - template: pre-job-steps.yml@imitation-cd # Configure variables, check out repos, Clear cache TEMPORARY - linked to imitation-cd instead of build-tools
              parameters:
                lvVersionToBuild:        ${{ lvVersionToBuild }}
                releaseVersion:          ${{ parameters.releaseVersion }}
                quarterlyReleaseVersion: ${{ parameters.quarterlyReleaseVersion }}
                archiveLocation:         ${{ parameters.archiveLocation }}
                buildOutputLocation:     ${{ parameters.buildOutputLocation }}

            - ${{ each buildStep in parameters.buildSteps }}:
              - template: build-op-steps.yml@imitation-cd # config file and build specs TEMPORARY - linked to imitation-cd instead of build-tools
                parameters:
                  buildStep:    ${{ buildStep }}
                  dependencies: ${{ parameters.dependencies }}

            - template: post-job-steps.yml@imitation-cd # nipkg and archive
              parameters:
                packages: ${{ parameters.packages }}
                pack:     ${{ parameters.pack }}
        # if all jobs have passed, place .finished file in top level archive location TEMPORARY - linked to imitation-cd instead of build-tools
      - job: Finalize
        displayName: Confirm All Builds Passed
        dependsOn:
          - ${{ each lvVersionToBuild in parameters.lvVersionsToBuild }}:
            - Job${{ lvVersionToBuild.version }}_${{ lvVersionToBuild.bitness }}
        condition: succeeded()
        steps:
          # archivePath defined in pre-job-steps.yml
        - powershell: |
            New-Item `
              -Path "${{ parameters.archiveLocation }}\NI\export\$(Build.SourceBranchName)\" `
              -Name ".finished" `
              -ItemType "File"